config/routes.rb
Rails.application.routes.draw do
  resources :labels, path: 'labels' do
    collection do
      get 'new', as: 'new_label'
      get ':id/edit', as: 'edit_label', action: :edit
    end
  end
  
  root 'tasks#index'

  resources :tasks do
    get 'search', on: :collection
  end

  resources :users, only: [:new, :create, :edit, :update, :show], as: :user do
    member do
      get 'edit', to: 'users#edit', as: :edit_user
    end
  end

  get '/signup', to: 'users#new', as: :new_user_form
  post '/signup', to: 'users#create', as: :create_user

  namespace :admin do
    resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      member do
        patch 'toggle_admin'
      end
    end
  end

  post 'login', to: 'sessions#create', as: :create_session
  get 'login', to: 'sessions#new', as: :new_session
  delete 'logout', to: 'sessions#destroy', as: :logout
  get '/logout', to: 'sessions#destroy', as: :logout_get
end

app/models/label.rb
class Label < ApplicationRecord
    belongs_to :user
    has_many :task_labels, dependent: :destroy
    has_many :tasks, through: :task_labels
  
    validates :name, presence: true, length: { maximum: 30 }
  
    scope :name_cont, ->(name) { where('name LIKE ?', "%#{name}%") if name.present? }
    scope :label_id_is, ->(label_id) { where(id: label_id) if label_id.present? }
  
    def self.search(params)
      labels = Label.all
      labels = labels.name_cont(params[:name_cont]) if params[:name_cont].present?
      labels = labels.label_id_is(params[:label_id_is]) if params[:label_id_is].present?
      labels
    end
  
    def task_ids=(ids)
      self.task_labels = ids.map{|id| TaskLabel.new(task_id: id)}
    end
  
    def task_ids
      self.task_labels.map(&:task_id)
    end
  end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! if email.present? }
  validates :email, uniqueness: { message: 'はすでに使用されています' }, confirmation: true, presence: true
  has_secure_password
  validates :name, presence: true
  validates :password, presence: true, confirmation: true, length: { minimum: 6 }, allow_blank: true
  attribute :admin, :boolean, default: false
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy

  before_destroy do
    if admin? && User.where(admin: true).count == 1
      errors.add(:admin, '権限を持つユーザが1人しかいないため、削除できません')
      throw :abort
    end
  end
  
  before_update do
    if admin_changed? && admin_was && User.where(admin: true).count == 1
      errors.add(:admin, '権限を持つユーザが1人しかいないため、更新できません')
      throw :abort
    end
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [ :show, :edit, :update, :destroy ]

  # GET /labels or /labels.json
  def index
    @search_params = label_search_params
    
    @labels = current_user.labels.search(@search_params)
  end  

  # GET /labels/1 or /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels or /labels.json
  def create
    @label = Label.new(label_params)
    @label.user = current_user
  
    respond_to do |format|
      if @label.save
        format.html { redirect_to labels_path, notice: t('.created') }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end  

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to labels_path, notice: t('.updated') }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: t('.destroyed') }
      format.json { head :no_content }
    end
  end

  private

    def set_label
      @label = current_user.labels.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = 'ラベルが見つかりませんでした'
      redirect_to labels_path
    end

    # Only allow a list of trusted parameters through.
    def label_params
      params.require(:label).permit(:name)
    end

    # Define label search parameters
    def label_search_params
      params.fetch(:search, {}).permit(:name_cont, :label_id_is)
    end
end

app/views/labels/_form.html.erb
<div class="container">
  <%= form_with(model: label, local: true) do |form| %>
    <% if label.errors.any? %>
      <div id="error_explanation">
        <h2><%= label.errors.count %> 件のエラーメッセージ</h2>

        <ul>
          <% label.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <% if label.new_record? %>
        <%= form.collection_check_boxes :task_ids, [], :id, :name, class: 'form-check-input' %>
      <% else %>
        <%= form.collection_check_boxes :task_ids, Label.all, :id, :name, class: 'form-check-input' %>
      <% end %>
    </div>

    <div class="form-group">
      <% if label.new_record? %>
        <%= form.submit t('helpers.submit.create', model: Label.model_name.human), class: 'btn btn-primary' %>
      <% else %>
        <%= form.submit t('helpers.submit.update', model: Label.model_name.human), class: 'btn btn-primary' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/labels/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', label: @label %>

<div class="form-group">
<%= link_to t("common.back"), labels_path, class: "btn btn-link" %>
</div>

app/views/labels/index.html.erb
<div class="container">
  <% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
  <% end %>

  <h1><%= t('.title') %></h1>

  <table class="table">
    <thead>
      <tr>
        <th><%= t("activerecord.attributes.label.name") %></th>
        <th><%= t("activerecord.attributes.label.tasks_count") %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @labels.each do |label| %>
        <tr>
          <td><%= label.name %></td>
          <td><%= label.tasks.count %></td>
          <td><%= link_to t("common.edit"), edit_label_path(label), class: "btn btn-primary edit-label" %></td>
          <td><%= link_to t("common.destroy"), label, method: :delete, class: "btn btn-danger destroy-label", data: { confirm: t('common.confirm_destroy') } %></td>
          <td>
            <% label.tasks.each do |task| %>
              <%= task.title %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/labels/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', label: @label %>

<div class="form-group">
<%= link_to t("common.back"), labels_path, class: "btn btn-link" %>
</div>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>
<div class="form-group">
<%= link_to t("common.edit"), edit_label_path(@label), class: "btn btn-primary" %> |
<%= link_to t("common.back"), labels_path, class: "btn btn-link" %>
</div>