config/routes.rb
Rails.application.routes.draw do
  resources :labels, path: 'labels' do
    collection do
      get 'new', as: 'new_label'
      get ':id/edit', as: 'edit_label', action: :edit
    end
  end
  
  root 'tasks#index'

  resources :tasks do
    get 'search', on: :collection
  end

  resources :users, only: [:new, :create, :edit, :update, :show], as: :user do
    member do
      get 'edit', to: 'users#edit', as: :edit_user
    end
  end

  get '/signup', to: 'users#new', as: :new_user_form
  post '/signup', to: 'users#create', as: :create_user

  namespace :admin do
    resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      member do
        patch 'toggle_admin'
      end
    end
  end

  post 'login', to: 'sessions#create', as: :create_session
  get 'login', to: 'sessions#new', as: :new_session
  delete 'logout', to: 'sessions#destroy', as: :logout
  get '/logout', to: 'sessions#destroy', as: :logout_get
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! if email.present? }
  validates :email, uniqueness: { message: 'はすでに使用されています' }, confirmation: true, presence: true
  has_secure_password
  validates :name, presence: true
  validates :password, presence: true, confirmation: true, length: { minimum: 6 }, allow_blank: true
  attribute :admin, :boolean, default: false
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy

  before_destroy do
    if admin? && User.where(admin: true).count == 1
      errors.add(:admin, '権限を持つユーザが1人しかいないため、削除できません')
      throw :abort
    end
  end
  
  before_update do
    if admin_changed? && admin_was && User.where(admin: true).count == 1
      errors.add(:admin, '権限を持つユーザが1人しかいないため、更新できません')
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :correct_user, only: [:edit, :update]
    before_action :require_admin, only: [:index, :destroy, :edit, :update, :create, :show, :new, :toggle_admin]
  
    def new
      @user = User.new
    end
  
    def index
      @users = User.all
    end
  
    def admin_index
      @admin_users = User.where(admin: true)
    end
  
    def create
      @user = User.new(user_params)
  
      if @user.save
        redirect_to admin_users_path, notice: t('.created')
      else
        flash.now[:alert] = t('admin.users.create_failed')
        render :new
      end
    end
  
    def show
      @user = User.find(params[:id])
      @tasks = @user.tasks.page(params[:page]).per(10)
    end
  
    def edit
      @user = User.find(params[:id])
    end
  
    def update
      @user = User.find(params[:id])
  
      if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
  
      if @user.update(user_params)
        redirect_to admin_users_path, notice: t('.updated')
      else
        if User.where(admin: true).count == 1
          flash[:alert] = '管理者権限を持つアカウントが0件になるため更新できません'
        end
        render 'admin/users/edit'
      end
    end
  
    def destroy
      @user = User.find(params[:id])
    
      if @user.admin? && User.where(admin: true).count == 1
        flash[:alert] = '管理者権限を持つアカウントが0件になるため削除できません'
        redirect_to admin_users_path
      elsif current_user == @user
        redirect_to admin_users_path, flash: { error: t('common.access_denied') }
      else
        if @user.tasks.delete_all && @user.destroy
          redirect_to admin_users_path, notice: t('.destroyed')
        else
          redirect_to admin_users_path, alert: t('.destroy_failed')
        end
      end
    end
  
    def toggle_admin
      @user = User.find(params[:id])
      @user.toggle(:admin)
      @user.save
      redirect_to admin_user_path(@user)
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
    end
  
    def correct_user
      @user = User.find(params[:id])
  
      unless current_user.admin? || (@user == current_user)
        redirect_to admin_users_path, flash: { error: t('common.access_denied') }
      end
    end
  
    def require_admin
      unless current_user&.admin?
        flash[:alert] = '管理者以外アクセスできません'
        redirect_to tasks_path, alert: '管理者以外アクセスできません'
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_admin, only: [:index, :destroy]
    before_action :correct_user, only: [:show, :edit, :update, :destroy]
    before_action :redirect_to_task_page, only: [:new, :create]
    before_action :require_login, except: [:new, :create]
  
    def new
      if current_user
        redirect_to tasks_path, notice: "すでにログインしています"
      else
        @user = User.new
      end
    end
  
    def index
      if current_user.admin?
        @users = User.all
      else
        flash[:alert] = "管理者以外アクセスできません"
        redirect_to tasks_path, alert: "管理者以外アクセスできません"
      end
    end
  
    def admin_index
      @admin_users = User.where(admin: true)
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        log_in(@user)
        redirect_to tasks_path, notice: t('.created')
      else
        render :new
      end
    end
  
    def edit
      @user = User.find(params[:id])
    end
  
    def update
      @user = User.find(params[:id])
      if params[:user][:password].blank? && params[:user][:password_confirmation].blank? && current_user == @user
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
      if @user.update(user_params)
        redirect_to user_path(@user), notice: t('.updated')
      else
        render :edit
      end
    end
  
    def show
      @user = User.find(params[:id])
      correct_user
    end
  
    def destroy
      @user = User.find(params[:id])
      if current_user.admin?
        if current_user == @user
          redirect_to users_path, flash: { error: t('common.access_denied') }
        else
          @user.tasks.destroy_all
          if @user.destroy
            redirect_to users_path, notice: t('.destroyed')
          else
            redirect_to users_path, alert: t('.destroy_failed')
          end
        end
      elsif current_user == @user
        redirect_to users_path, flash: { error: t('common.access_denied') }
      else
        redirect_to users_path, alert: t('common.access_denied')
      end
    end
  
    def toggle_admin
      @user = User.find(params[:id])
      @user.toggle(:admin)
      @user.save
      redirect_to admin_user_path(@user)
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  
    def correct_user
      @user = User.find(params[:id])
      unless current_user && (current_user.admin? || current_user == @user)
        redirect_to tasks_path, alert: '管理者以外アクセスできません'
      end
    end
  
    def require_admin
      unless current_user && current_user.admin?
        flash[:alert] = '管理者以外アクセスできません'
        redirect_to tasks_path, alert: '管理者以外アクセスできません'
      end
    end
    
    def require_login
      unless logged_in?
        session[:return_to] = request.url if request.get?
        redirect_to new_session_path, alert: 'ログインしてください'
      end
    end
    
    def logged_in?
      current_user.present?
    end
  
    def log_in(user)
      session[:user_id] = user.id
    end
  
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
  
    def redirect_to_task_page
      if current_user
        flash[:notice] = "ログアウトしてください"
        redirect_to tasks_path
      end
    end
end

app/views/users/_form.html.erb
<div class="container">
  <% if @user.new_record? %>
    <%= form_with(model: @user, url: create_user_path, local: true) do |form| %>
  <% else %>
    <%= form_with(model: @user, url: update_user_path(@user), local: true, method: "patch") do |form| %>
  <% end %>

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= @user.errors.count %> 件のエラーメッセージ </h2>

        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <div class="form-group">
      <% if @user.new_record? %>
        <%= form.submit t('helpers.submit.create', model: User.model_name.human), class: "btn btn-primary", id: "create-user" %>
      <% else %>
        <%= form.submit t('helpers.submit.update', model: User.model_name.human), class: "btn btn-primary", id: "update-user" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', user: @user %>

<%= link_to t('common.back'), user_path(@user), id: 'back', class: "btn btn-secondary" %>

app/views/users/new.html.erb
<div class="container">
  <h1><%= t('.title') %></h1>

  <%= form_with(model: @user, url: create_user_path, local: true) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= @user.errors.count %> 件のエラーメッセージ</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <table>        
    <div class="field">
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :email %><br>
      <%= form.text_field :email %>
    </div>

    <div class="field">
      <%= form.label :password %><br>
      <%= form.password_field :password %>
    </div>

    <div class="field">
      <%= form.label :password_confirmation %><br>
      <%= form.password_field :password_confirmation %>
    </div>
    </table>

    <div class="actions">
      <%= form.submit t('helpers.submit.create', model: User.model_name.human), id: "create-user", class: "btn btn-primary mt-3" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1><%= t('.title') %></h1>
  <p>
    <strong><%= User.human_attribute_name(:name) %></strong>
    <%= @user.name %>
  </p>
  <p>
    <strong><%= User.human_attribute_name(:email) %></strong>
    <%= @user.email %>
  </p>

  <%= link_to t('common.edit'), edit_user_path(@user), class: "btn btn-primary", id: 'edit-user' %>
</div>